<a href="https://colab.research.google.com/github/homo-du/2022-Machine-Learning-Specialization/blob/lab-code/tensorflow_implement.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import tensorflow as tf
import numpy as np

In [30]:
X = np.array([[0,0,0], [1,1,1], [1,0,0], [1,1,0], [0,0,1]])
y = np.array([[0],[1],[0],[1],[0]])
print(X)
print(y)
print ('The shape of X is: ' + str(X.shape))
print ('The shape of y is: ' + str(y.shape))

[[0 0 0]
 [1 1 1]
 [1 0 0]
 [1 1 0]
 [0 0 1]]
[[0]
 [1]
 [0]
 [1]
 [0]]
The shape of X is: (5, 3)
The shape of y is: (5, 1)


In [52]:
# 不经过softmax时输出的是概率，from_logits=True使softmax与损失函数合并计算，提升数值稳定
model = tf.keras.Sequential(
    [
        tf.keras.layers.Input(shape=(3,), name='input'),
        tf.keras.layers.Dense(20, activation='relu', name='L1'),
        tf.keras.layers.Dense(10, activation='relu', name='L2'),
        tf.keras.layers.Dense(5, activation='relu', name='L3'),
        tf.keras.layers.Dense(1, activation='sigmoid', name='L4'),
    ], name="my_model"
)
# 注意当前情况下输出层应该是1个unit

model.summary()

model.compile(loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
              optimizer='adam',)

model.fit(X, y, epochs=5)

x_test = np.array([[1,0,1]])
predictions = model.predict(x_test)
predictions

Model: "my_model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 L1 (Dense)                  (None, 20)                80        
                                                                 
 L2 (Dense)                  (None, 10)                210       
                                                                 
 L3 (Dense)                  (None, 5)                 55        
                                                                 
 L4 (Dense)                  (None, 1)                 6         
                                                                 
Total params: 351 (1.37 KB)
Trainable params: 351 (1.37 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
Epoch 1/5
1/1 [==============================] - 1s 864ms/step - loss: 0.6675
Epoch 2/5
1/1 [==============================] - 0s 9ms/step - loss: 0.6638
Epoch 

array([[0.47925377]], dtype=float32)

In [56]:
# softmax直接输出预测值
model = tf.keras.Sequential(
    [
        tf.keras.layers.Input(shape=(3,), name='input'),
        tf.keras.layers.Dense(20, activation='relu', name='L1'),
        tf.keras.layers.Dense(10, activation='relu', name='L2'),
        tf.keras.layers.Dense(5, activation='relu', name='L3'),
        tf.keras.layers.Dense(2, activation='softmax', name='L4'),
    ], name="my_model"
)

model.compile(loss=tf.keras.losses.BinaryCrossentropy(),
              optimizer='adam',)
y = np.array([[1,0],[0,1],[1,0],[0,1],[1,0]])

model.fit(X, y, epochs=5)

x_test = np.array([[0,0,1]])
predictions = model.predict(x_test)
predictions

Epoch 1/5
1/1 [==============================] - 1s 876ms/step - loss: 0.6893
Epoch 2/5
1/1 [==============================] - 0s 14ms/step - loss: 0.6887
Epoch 3/5
1/1 [==============================] - 0s 10ms/step - loss: 0.6881
Epoch 4/5
1/1 [==============================] - 0s 9ms/step - loss: 0.6875
Epoch 5/5
1/1 [==============================] - 0s 68ms/step


array([[0.48280373, 0.5171963 ]], dtype=float32)